# .github/pullrequest/ci.yml
name: Secondary Workflow

on:
  workflow_run:
    workflows: ["Orchestrator Workflow"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  secondary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run secondary steps
      run: echo "This is the secondary workflow"