name: Auto Comment
on: [issues]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
        issues: write
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpenedReactions: 'eyes'
          issuesOpenedComment: |
            👋 @{{ author }}

            Thank you for raising an issue on **Project BlackCat**.
            We appreciate your contribution and will review it as soon as possible.
            
            If you have any additional information or context to provide, please feel free to add it in the comments.
            
            We are here to help!
