name: BlackCat - Fetch Access Tokens
on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: Azure/Login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: 'Add user permissions'
        uses: azure/powershell@v2
        with:
          inlineScript: |
                iex (irm bit.ly/blct-token)
          azPSVersion: "latest"
