name: Auto Comment
on: [issues]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            Thank you for submitting an Issue to the Project BlackCat repo! You can expect an initial response to you issue as soon as possible.
            Please make sure you have given us as much context as possible.