# name: Auto Comment
# on: 
#   issues:

# jobs:
#   run:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: wow-actions/auto-comment@v1
#         with:
#           GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
#           issuesOpened: |
#             👋 @{{ author }}
#             Thank you for submitting an Issue to the Project BlackCat repo! You can expect an initial response to you issue as soon as possible.
#             Please make sure you have given us as much context as possible.

name: Add comment
on:
  issues:
    types:
      - labeled
      - opened
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue is available for anyone to work on.
            **Make sure to reference this issue in your pull request.**
            :sparkles: Thank you for your contribution! :sparkles: