name: Validate pull request
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
    # Main orchestration job
    orchestrate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

    # Call a reusable workflow (must be in .github/workflows directory)
    call-workflow:
        uses: ./.github/workflows/validate-version-update.yml@{ git.ref}
        permissions:
          contents: read
          pull-requests: read
