name: Workflow Orchestrator

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      workflows:
        description: 'Comma-separated list of workflows to run (leave empty for all)'
        required: false
        default: ''

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pull Request Workflows
        uses: actions/script@v6
        with:
          script: |
            const github = require('@actions/github');
            cost owner = github.context.repo.owner;
            const repo = github.context.repo.repo;
            const ref = github.context.ref;
            const workflow_id '.github/workflows/pullrequest/validate-version-update.yml';

            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: workflow_id,
              ref,
            });

            console.log(`Triggered workflow: ${workflow_id} on ref: ${ref}`);