name: Workflow Orchestrator

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      workflows:
        description: 'Comma-separated list of workflows to run (leave empty for all)'
        required: false
        default: ''

jobs:
  call-workflow:
    uses: ./.github/workflows/pester.yml
    