name: BlackCat - Read Identities
on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: Azure/Login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: 'Add user permissions'
        uses: azure/powershell@v2
        with:
          inlineScript: |

                $token = (Get-AzAccessToken -ResourceTypeName 'MSGraph').token | ConvertTo-SecureString -AsPlainText -Force
                Invoke-RestMethod -uri 'https://graph.microsoft.com/beta/users' -authentication Bearer -Token $token
                
          azPSVersion: "latest"
