name: Publish Module
on:
  workflow_dispatch:

jobs:
  sign_scripts:
    name: Sign and publish PowerShell scripts as pipeline artifacts
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Sign and Publish Module
        shell: pwsh
        env:
          PS_GALLERY_KEY: ${{ secrets.PS_GALLERY_KEY }}
        run: |
          Write-Host "Publishing module to PowerShell Gallery"

          $tempPath = '.\src\BlackCat\'
          # publish module
          Write-Host "Publishing module to PowerShell Gallery"

          # Set the path to the module
          Copy-Item .\Private\ -Recurse -Destination $tempPath -Force
          Copy-Item .\Public\ -Recurse -Destination $tempPath -Force
          Copy-Item .\BlackCat.psd1 -Destination $tempPath -Force
          Copy-Item .\BlackCat.psm1 -Destination $tempPath -Force

          # Publish the module to the PowerShell Gallery
          Publish-Module -Path "$tempPath" -NuGetApiKey $env:PS_GALLERY_KEY -Force -Verbose`

          # Remove the module from the local system
          Remove-Item -Path $tempPath -Recurse -Force -ErrorAction SilentlyContinue