
name: Publish Module
on:
  workflow_dispatch:

jobs:
  sign_scripts:
    name: Sign and publish PowerShell scripts as pipeline artifacts
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Sign and Publish Module
        shell: pwsh
        env:
          # SIGNING_CERTIFICATE:  ${{ secrets.SIGNING_CERTIFICATE }}
          # SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          PS_GALLERY_KEY: ${{ secrets.PS_GALLERY_KEY }}
        run: |
          Write-Host "Publishing module to PowerShell Gallery"

          # Exclude specific folders during publishing
          $excludePaths = @('.git', '.devcontainer', 'invokes', 'support-files')
          $tempPath = Join-Path -Path $env:TEMP -ChildPath "BlackCatTemp"
          Copy-Item .\ -Recurse -Destination $tempPath -Force
          ls $tempPath

          foreach ($path in $excludePaths) {
          Remove-Item -Path (Join-Path -Path $tempPath -ChildPath $path) -Recurse -Force -ErrorAction SilentlyContinue
          }

          Publish-Module -Path $tempPath -NuGetApiKey $env:PS_GALLERY_KEY -Force -Verbose
          Remove-Item -Path $tempPath -Recurse -Force -ErrorAction SilentlyContinue
