name: Publish Module
on:
  workflow_dispatch:

jobs:
  sign_scripts:
    name: Sign and publish PowerShell scripts as pipeline artifacts
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Sign and Publish Module
        shell: pwsh
        env:
          PS_GALLERY_KEY: ${{ secrets.PS_GALLERY_KEY }}
        run: |
          Write-Host "Publishing module to PowerShell Gallery"

          # Exclude specific folders during publishing
          $excludePaths = @('.git', '.devcontainer', 'invokes', 'support-files')
          $tempPath = Join-Path -Path $env:TEMP -ChildPath "BlackCatTemp"
          Copy-Item .\ -Recurse -Destination $tempPath -Force
          Write-Host "Contents of $tempPath after copy:"
          Get-ChildItem -Path $tempPath -Recurse

          foreach ($path in $excludePaths) {
            Remove-Item -Path (Join-Path -Path $tempPath -ChildPath $path) -Recurse -Force -ErrorAction SilentlyContinue
          }

          Write-Host "Contents of $tempPath after exclusion:"
          Get-ChildItem -Path $tempPath -Recurse

          # Verify module validity
          if (Test-Path -Path (Join-Path -Path $tempPath -ChildPath 'ModuleManifest.psd1')) {
            Publish-Module -Path $tempPath -NuGetApiKey $env:PS_GALLERY_KEY -Force -Verbose
          } else {
            Write-Error "No valid module found in the specified path."
            exit 1
          }

          Remove-Item -Path $tempPath -Recurse -Force -ErrorAction SilentlyContinue