name: Secure Azure Token Exchange

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC token request
  contents: read

jobs:
  exchange-token:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Request GitHub OIDC token
      - name: Request OIDC Token
        id: oidc_token
        uses: actions/github-script@v6
        with:
          script: |
            const id_token = await core.getIDToken();
            core.setOutput('token', id_token);
            core.exportVariable('OIDC_TOKEN', id_token);

      # Step 2: Validate environment variables
      - name: Validate environment variables
        shell: pwsh
        env:
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          UAMI_CLIENT_ID: ${{ secrets.UAMI_CLIENT_ID }}
          APP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          GRAPH_SCOPE: https://graph.microsoft.com/.default
        run: |
          # Documentation: This step validates that all required environment variables are set
          # before attempting to exchange tokens.
          
          if (-not $env:TENANT_ID) { Write-Host "❌ TENANT_ID not set."; exit 1 }
          if (-not $env:APP_CLIENT_ID) { Write-Host "❌ APP_CLIENT_ID not set."; exit 1 }
          if (-not $env:GRAPH_SCOPE) { Write-Host "❌ GRAPH_SCOPE not set."; exit 1 }
          if (-not $env:OIDC_TOKEN) { Write-Host "❌ OIDC_TOKEN not set."; exit 1 }
          if ($env:OIDC_TOKEN -notmatch '\.') { Write-Host "❌ OIDC_TOKEN is not a valid JWT."; exit 1 }
          Write-Host "✅ All environment variables are set correctly."

      # Step 3: Exchange OIDC token for Azure access token
      - name: Exchange OIDC Token for Azure Token
        shell: pwsh
        env:
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          APP_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          GRAPH_SCOPE: https://graph.microsoft.com/.default
          CLIENT_ASSERTION_TYPE: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
        run: |
          # Documentation: This step exchanges the GitHub OIDC token for an Azure AD access token
          # using federated credential authentication.
          
          Add-Type -AssemblyName System.Web
          
          $body = @{  
            client_id             = $env:APP_CLIENT_ID
            grant_type            = "client_credentials" 
            scope                 = $env:GRAPH_SCOPE
            client_assertion_type = $env:CLIENT_ASSERTION_TYPE
            client_assertion      = $env:OIDC_TOKEN  # GitHub OIDC token
          }

          function ConvertTo-FormData($hash) {
            return ($hash.GetEnumerator() | ForEach-Object {
              [System.Web.HttpUtility]::UrlEncode($_.Key) + "=" + [System.Web.HttpUtility]::UrlEncode($_.Value)
            }) -join "&"
          }

          $bodyEncoded = ConvertTo-FormData $body
          $tokenUrl = "https://login.microsoftonline.com/$env:TENANT_ID/oauth2/v2.0/token"
          
          try {
            $resp = Invoke-RestMethod -Method Post -Uri $tokenUrl -Body $bodyEncoded -ContentType "application/x-www-form-urlencoded"
            
            if (-not $resp.access_token) { 
              throw "Azure token exchange failed - no access token in response" 
            }
            
            "MI_TOKEN=$($resp.access_token)" | Out-File -FilePath $env:GITHUB_ENV -Append
            Write-Host "Azure token acquired (first 20 chars): $($resp.access_token.Substring(0,20))"
          }
          catch {
            Write-Host "❌ Azure token exchange failed: $_"
            exit 1
          }
